# Release a new plugin version.
# trigger:
# modify manifest.json, package.json, versions.json
# git tag <version number>
# git push origin --tags

name: Release A New Version

on:
  push:
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REMOTELYSAVE_WEBSITE: ${{secrets.REMOTELYSAVE_WEBSITE}}
      REMOTELYSAVE_CLIENT_ID: ${{secrets.REMOTELYSAVE_CLIENT_ID}}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout LFS file list
        run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id
      - name: LFS Cache
        uses: actions/cache@v4
        with:
          path: .git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: |
            ${{ runner.os }}-lfs-
      - name: Git LFS Pull
        run: git lfs pull
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Create Release And Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.main.js
            manifest.json
            styles.css
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          make_latest: true
